/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kewenc_mp3encoder_Mp3Encoder */

#ifndef _Included_com_kewenc_mp3encoder_Mp3Encoder
#define _Included_com_kewenc_mp3encoder_Mp3Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kewenc_mp3encoder_Mp3Encoder
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kewenc_mp3encoder_Mp3Encoder_encode
  (JNIEnv *, jobject);

/*
 * Class:     com_kewenc_mp3encoder_Mp3Encoder
 * Method:    getLog
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kewenc_mp3encoder_Mp3Encoder_getLog
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
